IBM-MQ polling inbound
wso2-incubator/esb-inbound-ibmmq pull request #1
Opened 2017-07-06 20:07 UTC by hasithajayasundara

2017-07-27 09:00 UTC, djkevincr requested changes

2017-07-27 09:00 UTC, djkevincr commented on src/main/java/org/wso2/carbon/inbound/custom/poll/MQPollingInbound.java
> +import com.ibm.mq.*;
Shall we do this imports separately?

2017-07-27 09:08 UTC, hasithajayasundara commented on src/main/java/org/wso2/carbon/inbound/custom/poll/MQPollingInbound.java
> +import com.ibm.mq.*;
Done..!

2017-08-03 06:41 UTC, djkevincr commented on ibmmqpollinginbound.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove this intellij idea generated files.

2017-08-03 06:42 UTC, djkevincr commented on org.apache.synapse.custom.poll.class.iml
> +<module org.jetbrains.idea.maven.project.MavenProjectsManager.isMavenModule="true" type="JAVA_MODULE" version="4">
Please remove this intellij idea generated files.

2017-08-03 06:44 UTC, djkevincr commented on pom.xml
> +
Please remove this unnecessary new lines.

2017-08-03 06:46 UTC, djkevincr commented on src/main/java/org/wso2/carbon/inbound/custom/poll/MQConfiguration.java
> +    public int getmaxConnections() {
Please properly document this public methods for all cases.

2017-08-03 06:49 UTC, djkevincr commented on src/main/java/org/wso2/carbon/inbound/custom/poll/MQConnectionBuilder.java
> +public class MQConnectionBuilder {
Please make this class a utility class MQConnectionUtils and remove all the class level variable. You need to address all stuff discussed in the IBM-MQ connector PR. [1]
[1] https://github.com/wso2-incubator/esb-connector-ibmmq/pull/1

2017-08-03 06:50 UTC, djkevincr commented on src/main/java/org/wso2/carbon/inbound/custom/poll/MQConstant.java
> +
Please remove this unnecessary new lines.

2017-08-03 06:51 UTC, djkevincr commented on src/test/java/org/wso2/carbon/inbound/ibmmqintegrationTest.java
> +public class ibmmqintegrationTest {
IbmmqintegrationTest

2017-08-03 06:51 UTC, djkevincr commented on src/test/java/org/wso2/carbon/inbound/ibmmqintegrationTest.java
> + * Created by hasitha on 7/7/17.
Please remove this Intellij idea generated comments.

2017-08-03 07:04 UTC, djkevincr commented on src/main/java/org/wso2/carbon/inbound/custom/poll/MQPollingInbound.java
> +                if (message.getStringProperty("ContentType") != null) {
Please check whether the correct message builders are invoked for IBM-MQ content types. Please test this at least for json and xml content types.

2017-08-03 07:08 UTC, djkevincr commented on src/main/java/org/wso2/carbon/inbound/custom/poll/MQPollingInbound.java
> +            logger.error("Error removing services");
Exception is dropped from the log error. Please include exception in log.
logger.error("Error removing services", e);

2017-08-03 07:09 UTC, djkevincr commented on src/main/java/org/wso2/carbon/inbound/custom/poll/MQPollingInbound.java
> +
Please remove this unnecessary new line.

2017-08-03 07:10 UTC, djkevincr commented on src/main/java/org/wso2/carbon/inbound/custom/poll/MQPollingInbound.java
> +            logger.info("Queue is empty");
This should be a error log and exception is dropped - logger.("Message", e);

2017-08-03 07:11 UTC, djkevincr commented on src/main/java/org/wso2/carbon/inbound/custom/poll/MQPollingInbound.java
> +                logger.info("A message received");
May be this should be a debug log.

2017-08-03 07:18 UTC, djkevincr commented
Please note you should remove all the proprietary IBM binary files committed from the PR.
com.ibm.mq.allclient.jar, com.ibm.mq.allclient.jar, com.ibm.mq.allclient.jar

2017-08-03 07:42 UTC, djkevincr commented
Current implementation supports polling messages on queue, I think we need to extend this implementation to support topics as well.

2017-08-04 04:57 UTC, hmrajas commented on src/main/java/org/wso2/carbon/inbound/custom/poll/MQConnectionBuilder.java
> +
Why this empty catch block?

2017-08-04 04:57 UTC, hmrajas commented on src/main/java/org/wso2/carbon/inbound/custom/poll/MQConnectionBuilder.java
> +            }
Empty catch block?

2024-02-01 20:33 UTC, closed without merging